"""
Bulk Sync Child Work Item States to Match Parent State.

Self-contained one-off script that finds parent→child pairs and updates each
child's State to match its parent's State.

Can operate in three modes:
  1. **From report:** Read the Excel report generated by bulk_create_children.py
     and sync states for all CREATED or SKIPPED — child already exists rows.
  2. **From parent query:** Run a saved query that returns parent work items,
     discover children via ADO relations, and sync states.
  3. **From children query:** Run a saved query that returns child work items,
     look up each child's parent via ADO relations, and sync states.

Only children whose state differs from their parent are updated.

Usage
-----
  # From a previous bulk creation report (dry run first)
  python scripts/bulk_sync_child_states.py \\
    --project "MyProject" \\
    --from-report bulk_children_report.xlsx \\
    --dry-run

  # Execute the state sync
  python scripts/bulk_sync_child_states.py \\
    --project "MyProject" \\
    --from-report bulk_children_report.xlsx

  # From a saved ADO query returning parent items (discovers children automatically)
  python scripts/bulk_sync_child_states.py \\
    --project "MyProject" \\
    --query-id "a1b2c3d4-e5f6-7890-abcd-ef1234567890" \\
    --dry-run

  # From a saved ADO query returning child items (looks up parents automatically)
  python scripts/bulk_sync_child_states.py \\
    --project "MyProject" \\
    --children-query-id "a1b2c3d4-e5f6-7890-abcd-ef1234567890" \\
    --dry-run

  # From explicit types + states
  python scripts/bulk_sync_child_states.py \\
    --project "MyProject" \\
    --types "User Story,Bug" \\
    --states "Ready for Development,In Progress,Active"

Authentication
--------------
Uses DefaultAzureCredential (Azure CLI locally, Managed Identity in Azure).
Requires: `az login` before running locally.

Dependencies
------------
  pip install httpx openpyxl azure-identity
"""

from __future__ import annotations

import argparse
import logging
import os
import time
from typing import Any

import httpx
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("bulk_sync_child_states")

# ADO API version
ADO_API_VERSION = "7.1"

# Azure AD resource ID for ADO
ADO_RESOURCE_ID = "499b84ac-1321-427f-aa17-267ca6975798"

# Refresh token 5 minutes before actual expiry
TOKEN_REFRESH_BUFFER_SECONDS = 300

# Default organization (can be overridden with --org)
DEFAULT_ORG = os.environ.get("ADO_ORGANIZATION", "BrandtInfoServices")

# Field reference names (inlined — no dependency on config.py)
TITLE = "System.Title"
STATE = "System.State"
WORK_ITEM_TYPE = "System.WorkItemType"
TEAM_PROJECT = "System.TeamProject"
CLIENT_REQUESTED = os.environ.get("ADO_FIELD_CLIENT_REQUESTED", "Custom.ClientRequested")
CLIENT_SELECTION_PORTAL = os.environ.get("ADO_FIELD_CLIENT_SELECTION_PORTAL", "Custom.ClientSelectionforPortalVisibility")

# Parent→child type mapping (same as bulk_create_children.py)
PARENT_TO_CHILD: dict[str, str] = {
    "User Story": "Client Story Work Item",
    "Issue": "Client Story Work Item",
    "Epic": "Client Epic Work Item",
    "Bug": "Client Bug Work Item",
    "Initiative": "Client Initiative Work Item",
    "Feature": "Client Feature Work Item",
}

ALL_PARENT_TYPES: set[str] = set(PARENT_TO_CHILD.keys())


# ---------------------------------------------------------------------------
# Lightweight ADO HTTP client (same as bulk_create_children.py)
# ---------------------------------------------------------------------------

class AdoClient:
    """Minimal ADO REST API client using DefaultAzureCredential."""

    def __init__(self, org: str) -> None:
        self._org = org
        self._base_url = f"https://dev.azure.com/{org}/_apis"
        self._credential = None
        self._cached_token: str | None = None
        self._token_expires_at: float = 0.0
        self._client = httpx.Client(
            headers={"Content-Type": "application/json-patch+json"},
            timeout=30.0,
            event_hooks={"request": [self._inject_auth]},
        )

    def _inject_auth(self, request: httpx.Request) -> None:
        token = self._get_token()
        request.headers["Authorization"] = f"Bearer {token}"

    def _get_token(self) -> str:
        now = time.time()
        if self._cached_token and now < self._token_expires_at:
            return self._cached_token

        if self._credential is None:
            from azure.identity import DefaultAzureCredential
            self._credential = DefaultAzureCredential()

        token = self._credential.get_token(f"{ADO_RESOURCE_ID}/.default")
        self._cached_token = token.token
        self._token_expires_at = token.expires_on - TOKEN_REFRESH_BUFFER_SECONDS
        logger.info("Acquired ADO bearer token (expires in %ds)", int(token.expires_on - now))
        return self._cached_token

    def _project_url(self, project: str) -> str:
        return f"https://dev.azure.com/{self._org}/{project}/_apis"

    def close(self) -> None:
        self._client.close()

    def get_work_item(self, work_item_id: int, expand: str = "all") -> dict[str, Any]:
        url = f"{self._base_url}/wit/workitems/{work_item_id}"
        params = {"api-version": ADO_API_VERSION, "$expand": expand}
        resp = self._client.get(url, params=params)
        resp.raise_for_status()
        return resp.json()

    def get_child_work_items(self, parent_id: int) -> list[dict[str, Any]]:
        """Fetch child work items linked to a parent via Hierarchy-Forward relations."""
        parent = self.get_work_item(parent_id, expand="relations")
        relations = parent.get("relations", []) or []

        child_urls = [
            rel["url"]
            for rel in relations
            if rel.get("rel") == "System.LinkTypes.Hierarchy-Forward"
        ]
        if not child_urls:
            return []

        children: list[dict[str, Any]] = []
        for url in child_urls:
            try:
                child_id = int(url.rstrip("/").split("/")[-1])
                child = self.get_work_item(child_id)
                children.append(child)
            except Exception as e:
                logger.warning("Failed to fetch child from %s: %s", url, e)
        return children

    def run_wiql(self, project: str, wiql: str) -> list[int]:
        url = f"{self._project_url(project)}/wit/wiql"
        params = {"api-version": ADO_API_VERSION}
        resp = self._client.post(
            url, params=params, json={"query": wiql},
            headers={"Content-Type": "application/json"},
        )
        resp.raise_for_status()
        rows = resp.json().get("workItems", [])
        return [row["id"] for row in rows]

    def run_saved_query(self, project: str, query_id: str) -> list[int]:
        url = f"{self._project_url(project)}/wit/wiql/{query_id}"
        params = {"api-version": ADO_API_VERSION}
        resp = self._client.get(url, params=params)
        resp.raise_for_status()
        data = resp.json()
        query_name = data.get("queryName", data.get("name", query_id))
        logger.info("Query name: %s", query_name)
        rows = data.get("workItems", [])
        return [row["id"] for row in rows]

    def get_parent_id(self, child_id: int) -> int | None:
        """Look up a child's parent ID via Hierarchy-Reverse relation."""
        wi = self.get_work_item(child_id, expand="relations")
        relations = wi.get("relations", []) or []
        for rel in relations:
            if rel.get("rel") == "System.LinkTypes.Hierarchy-Reverse":
                try:
                    return int(rel["url"].rstrip("/").split("/")[-1])
                except (ValueError, KeyError):
                    pass
        return None

    def update_work_item_state(self, work_item_id: int, new_state: str) -> dict[str, Any]:
        """Update a work item's State field."""
        url = f"{self._base_url}/wit/workitems/{work_item_id}"
        params = {"api-version": ADO_API_VERSION}
        operations = [{"op": "add", "path": f"/fields/{STATE}", "value": new_state}]
        resp = self._client.patch(url, params=params, json=operations)
        resp.raise_for_status()
        return resp.json()


# ---------------------------------------------------------------------------
# Read parent→child pairs from an existing report
# ---------------------------------------------------------------------------

def _read_pairs_from_report(report_path: str) -> list[tuple[int, int]]:
    """
    Read parent→child ID pairs from a bulk_create_children report.

    Reads the Excel file and returns (parent_id, child_id) for every row
    that has both a Parent ID and a Child Work Item ID (i.e., CREATED or
    SKIPPED — child already exists rows).
    """
    wb = load_workbook(report_path, read_only=True)
    ws = wb.active

    pairs: list[tuple[int, int]] = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        parent_id = row[0]  # Column A: Parent ID
        child_id = row[4]   # Column E: Child Work Item ID

        if parent_id and child_id:
            try:
                pairs.append((int(parent_id), int(child_id)))
            except (ValueError, TypeError):
                continue

    wb.close()
    logger.info("Read %d parent→child pairs from %s", len(pairs), report_path)
    return pairs


# ---------------------------------------------------------------------------
# Discover parent→child pairs from ADO query
# ---------------------------------------------------------------------------

def _discover_pairs_from_query(
    ado: AdoClient,
    project: str,
    parent_ids: list[int],
) -> list[tuple[int, int]]:
    """
    For each parent, find all child work items via ADO relations.

    Returns (parent_id, child_id) for every child of a matching type.
    """
    pairs: list[tuple[int, int]] = []

    for i, parent_id in enumerate(parent_ids, 1):
        logger.info("[%d/%d] Discovering children of parent %d", i, len(parent_ids), parent_id)
        try:
            children = ado.get_child_work_items(parent_id)
            parent_wi = ado.get_work_item(parent_id)
            parent_type = parent_wi.get("fields", {}).get(WORK_ITEM_TYPE, "")
            expected_child_type = PARENT_TO_CHILD.get(parent_type)

            for child in children:
                child_fields = child.get("fields", {})
                child_type = child_fields.get(WORK_ITEM_TYPE, "")
                if expected_child_type and child_type == expected_child_type:
                    pairs.append((parent_id, child["id"]))
        except Exception as e:
            logger.error("Error discovering children for parent %d: %s", parent_id, e)

    logger.info("Discovered %d parent→child pairs", len(pairs))
    return pairs


def _discover_pairs_from_children(
    ado: AdoClient,
    child_ids: list[int],
) -> list[tuple[int, int]]:
    """
    For each child work item, look up its parent via ADO relations.

    Only includes children whose type is a known child type (Client Story Work
    Item, Client Epic Work Item, etc.) to avoid syncing unrelated work items.

    Returns (parent_id, child_id) pairs.
    """
    all_child_types: set[str] = set(PARENT_TO_CHILD.values())
    pairs: list[tuple[int, int]] = []

    for i, child_id in enumerate(child_ids, 1):
        if i % 50 == 0 or i == 1:
            logger.info("[%d/%d] Looking up parent for child %d", i, len(child_ids), child_id)
        try:
            # Fetch child to verify it's a known child type
            child_wi = ado.get_work_item(child_id, expand="relations")
            child_type = child_wi.get("fields", {}).get(WORK_ITEM_TYPE, "")

            if child_type not in all_child_types:
                logger.debug(
                    "  Skipping %d — type '%s' is not a known child type",
                    child_id, child_type,
                )
                continue

            # Find parent via Hierarchy-Reverse relation
            relations = child_wi.get("relations", []) or []
            parent_id: int | None = None
            for rel in relations:
                if rel.get("rel") == "System.LinkTypes.Hierarchy-Reverse":
                    try:
                        parent_id = int(rel["url"].rstrip("/").split("/")[-1])
                    except (ValueError, KeyError):
                        pass
                    break

            if parent_id is None:
                logger.debug("  Child %d has no parent link — skipping", child_id)
                continue

            pairs.append((parent_id, child_id))

        except Exception as e:
            logger.error("Error looking up parent for child %d: %s", child_id, e)

    logger.info("Discovered %d parent→child pairs from %d children", len(pairs), len(child_ids))
    return pairs


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def _generate_report(
    results: list[dict[str, Any]],
    output_path: str,
    org: str,
) -> None:
    """Generate an Excel report of state sync results."""
    wb = Workbook()
    ws = wb.active
    ws.title = "State Sync Report"

    header_font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill("solid", fgColor="4472C4")
    header_alignment = Alignment(horizontal="center", vertical="center")

    headers = [
        "Parent ID",
        "Parent Title",
        "Parent State",
        "Child ID",
        "Child Client",
        "Child State (Before)",
        "Child State (After)",
        "Status",
    ]

    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment

    data_font = Font(name="Arial", size=10)
    wrap_alignment = Alignment(vertical="top", wrap_text=True)

    for row_idx, result in enumerate(results, 2):
        row_data = [
            result.get("parent_id", ""),
            result.get("parent_title", ""),
            result.get("parent_state", ""),
            result.get("child_id", ""),
            result.get("child_client", ""),
            result.get("child_state_before", ""),
            result.get("child_state_after", ""),
            result.get("status", ""),
        ]
        for col_idx, value in enumerate(row_data, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.font = data_font
            cell.alignment = wrap_alignment

    col_widths = [12, 40, 25, 12, 30, 22, 22, 20]
    for col_idx, width in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:H{len(results) + 1}"

    wb.save(output_path)
    logger.info("Report saved to %s (%d rows)", output_path, len(results))


# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------

def bulk_sync_states(
    project: str,
    org: str,
    from_report: str = "",
    work_item_types: list[str] | None = None,
    states: list[str] | None = None,
    query_id: str = "",
    children_query_id: str = "",
    output_path: str = "bulk_state_sync_report.xlsx",
    dry_run: bool = False,
) -> None:
    """Find parent→child pairs and sync child states to match parents."""
    ado = AdoClient(org)
    results: list[dict[str, Any]] = []

    try:
        # 1. Get parent→child pairs
        if from_report:
            pairs = _read_pairs_from_report(from_report)
        elif children_query_id:
            logger.info("Running saved query (children): %s", children_query_id)
            child_ids = ado.run_saved_query(project, children_query_id)
            logger.info("Query returned %d child work items", len(child_ids))
            pairs = _discover_pairs_from_children(ado, child_ids)
        elif query_id:
            logger.info("Running saved query (parents): %s", query_id)
            parent_ids = ado.run_saved_query(project, query_id)
            logger.info("Query returned %d work items", len(parent_ids))
            pairs = _discover_pairs_from_query(ado, project, parent_ids)
        else:
            type_clauses = " OR ".join(
                f"[System.WorkItemType] = '{t}'" for t in (work_item_types or [])
            )
            state_clauses = " OR ".join(
                f"[System.State] = '{s}'" for s in (states or [])
            )
            wiql = (
                f"SELECT [System.Id] FROM workitems "
                f"WHERE [System.TeamProject] = '{project}' "
                f"AND ({type_clauses}) "
                f"AND ({state_clauses}) "
                f"ORDER BY [System.Id] ASC"
            )
            logger.info("Running WIQL query:\n  %s", wiql)
            parent_ids = ado.run_wiql(project, wiql)
            logger.info("Query returned %d work items", len(parent_ids))
            pairs = _discover_pairs_from_query(ado, project, parent_ids)

        if not pairs:
            logger.info("No parent→child pairs found. Nothing to do.")
            return

        logger.info(
            "Processing %d parent→child pairs (dry_run=%s)",
            len(pairs), dry_run,
        )

        # Cache parent data to avoid re-fetching when a parent has multiple children
        parent_cache: dict[int, dict[str, Any]] = {}

        updated_count = 0
        skipped_count = 0
        error_count = 0

        for i, (parent_id, child_id) in enumerate(pairs, 1):
            logger.info("--- [%d/%d] Parent %d → Child %d ---", i, len(pairs), parent_id, child_id)

            try:
                # Fetch parent (with cache)
                if parent_id not in parent_cache:
                    parent_wi = ado.get_work_item(parent_id)
                    parent_cache[parent_id] = parent_wi.get("fields", {})
                parent_fields = parent_cache[parent_id]

                parent_state = parent_fields.get(STATE, "")
                parent_title = parent_fields.get(TITLE, "")

                # Fetch child
                child_wi = ado.get_work_item(child_id)
                child_fields = child_wi.get("fields", {})
                child_state = child_fields.get(STATE, "")
                child_client = child_fields.get(CLIENT_REQUESTED, "")

                if child_state == parent_state:
                    logger.info(
                        "  State already matches (%s) — skipping", child_state,
                    )
                    results.append({
                        "parent_id": parent_id,
                        "parent_title": parent_title,
                        "parent_state": parent_state,
                        "child_id": child_id,
                        "child_client": child_client,
                        "child_state_before": child_state,
                        "child_state_after": child_state,
                        "status": "SKIPPED — already matches",
                    })
                    skipped_count += 1
                    continue

                if dry_run:
                    logger.info(
                        "  [DRY RUN] Would update child %d state: %s → %s",
                        child_id, child_state, parent_state,
                    )
                    results.append({
                        "parent_id": parent_id,
                        "parent_title": parent_title,
                        "parent_state": parent_state,
                        "child_id": child_id,
                        "child_client": child_client,
                        "child_state_before": child_state,
                        "child_state_after": parent_state,
                        "status": "DRY RUN — would update",
                    })
                    continue

                # Update child state
                ado.update_work_item_state(child_id, parent_state)
                logger.info(
                    "  Updated child %d state: %s → %s",
                    child_id, child_state, parent_state,
                )
                results.append({
                    "parent_id": parent_id,
                    "parent_title": parent_title,
                    "parent_state": parent_state,
                    "child_id": child_id,
                    "child_client": child_client,
                    "child_state_before": child_state,
                    "child_state_after": parent_state,
                    "status": "UPDATED",
                })
                updated_count += 1

            except Exception as e:
                logger.error("  Error syncing child %d: %s", child_id, e)
                results.append({
                    "parent_id": parent_id,
                    "parent_title": "",
                    "parent_state": "",
                    "child_id": child_id,
                    "child_client": "",
                    "child_state_before": "",
                    "child_state_after": "",
                    "status": f"ERROR — {str(e)[:200]}",
                })
                error_count += 1

        # Summary
        logger.info("=" * 60)
        logger.info("SUMMARY")
        logger.info("  Total pairs processed:  %d", len(pairs))
        logger.info("  States updated:         %d", updated_count)
        logger.info("  Skipped (already match): %d", skipped_count)
        logger.info("  Errors:                 %d", error_count)
        logger.info("=" * 60)

        # Generate report
        if results:
            _generate_report(results, output_path, org)

    finally:
        ado.close()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Bulk sync child work item states to match their parent state.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--project",
        required=True,
        help="ADO project name (e.g., 'MyProject')",
    )

    source = parser.add_mutually_exclusive_group()
    source.add_argument(
        "--from-report",
        help="Path to bulk_children_report.xlsx from a previous bulk_create_children run. "
             "Reads parent→child pairs directly from the report.",
    )
    source.add_argument(
        "--query-id",
        help="GUID of a saved ADO query returning PARENT work items. Discovers children via ADO relations.",
    )
    source.add_argument(
        "--children-query-id",
        help="GUID of a saved ADO query returning CHILD work items. Looks up each child's parent via ADO relations.",
    )

    parser.add_argument(
        "--types",
        help="Comma-separated parent work item types (e.g., 'User Story,Bug'). "
             "Used with --states when --from-report and --query-id are not provided.",
    )
    parser.add_argument(
        "--states",
        help="Comma-separated work item states to match (e.g., 'Ready for Development,In Progress'). "
             "Used with --types when --from-report and --query-id are not provided.",
    )
    parser.add_argument(
        "--output",
        default="bulk_state_sync_report.xlsx",
        help="Output Excel file path (default: bulk_state_sync_report.xlsx)",
    )
    parser.add_argument(
        "--org",
        default=DEFAULT_ORG,
        help=f"ADO organization name (default: {DEFAULT_ORG})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be updated without making changes",
    )

    args = parser.parse_args()

    # Validate: need one of --from-report, --query-id, --children-query-id, or (--types AND --states)
    if not args.from_report and not args.query_id and not args.children_query_id:
        if not args.types:
            parser.error("--types is required when --from-report, --query-id, and --children-query-id are not provided")
        if not args.states:
            parser.error("--states is required when --from-report, --query-id, and --children-query-id are not provided")

    work_item_types: list[str] = []
    states: list[str] = []

    if args.types:
        work_item_types = [t.strip() for t in args.types.split(",") if t.strip()]
    if args.states:
        states = [s.strip() for s in args.states.split(",") if s.strip()]

    bulk_sync_states(
        project=args.project,
        org=args.org,
        from_report=args.from_report or "",
        work_item_types=work_item_types if work_item_types else None,
        states=states if states else None,
        query_id=args.query_id or "",
        children_query_id=args.children_query_id or "",
        output_path=args.output,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
